---
- hosts: "all"
  become: true
  gather_facts: false

  tasks:
  - name: "Install Python"
    raw: "apt-get -y -q install python"

- hosts: "tag_role_node,tag_role_etcd"
  become: true
  gather_facts: true

  roles:
    - kubeadm-install

- hosts: "tag_role_node[0]"
  become: true
  gather_facts: true

  roles:
    - etcd-ca

- hosts: "tag_role_etcd"
  become: true
  gather_facts: true

  roles:
    - etcd
